# Environment for developing deconvolution scripts
# TODO: remove unnecessary deps.

name: deconv

channels:
 - defaults
 - conda-forge

dependencies:
 - python=3.7
 - numpy
 - cython
 - joblib
 - pandas
 - openpyxl
 - pip
 - xlrd
 - matplotlib
 - scipy
 - emcee
 - boost-cpp
 - jupyter
 - black
 - pylint
 - numba
 - rope
 - pylint
 - logzero
 - pymc3
 - flake8
 - dask
 - chardet
